//
//  UserInteractor.swift
//  HSE Clubs
//
//  Created by Ярослав Ульяненков on 08.03.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import Alamofire

protocol UserBusinessLogic
{
    func getUserData(request: User.Request)
}

protocol UserDataStore
{
    //var name: String { get set }
}

class UserInteractor: UserBusinessLogic, UserDataStore
{
    var presenter: UserPresentationLogic?
    var worker: UserWorker?
    //var name: String = ""
    
    // MARK: Do something
    
    func getUserData(request: User.Request)
    {
        DispatchQueue.global().async {
            guard let url = RequestRoutes.getRoute(.getUser(request.uniqueName)) else {return}
            AF.request(url, method: .get).responseDecodable(of: User.Response.self) { response in
                print(response.result)
                
                switch response.result {
                case .success:
                    guard let user = response.value else { return }
                    self.presenter?.presentUser(response: user)
                case .failure(let error):
                    print("Error:", error)
                }
            }
        }
    }
}
