//
//  UserModels.swift
//  HSE Clubs
//
//  Created by Ярослав Ульяненков on 08.03.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum User
{
    // MARK: Use cases
    
    struct Request: Codable
    {
        let uniqueName: String
        public init() {
            uniqueName = UserDefaults.standard.string(forKey: "unique_name") ?? ""
        }
    }
    struct Response: Codable
    {
        let id: Int?
        let uniqueName: String?
        let name: String?
        let email: String?
        let vk: String?
        let telegram: String?
        let photoPath: String?
        let isShowContacts: Bool?
//        let clubs: [Any]?
    }
    struct ViewModel
    {
    }
}
