//
//  ClubPresenter.swift
//  HSE Clubs
//
//  Created by Ярослав Ульяненков on 14.03.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ClubPresentationLogic
{
  func presentSomething(response: ClubData.Something.Response)
}

class ClubPresenter: ClubPresentationLogic
{
  weak var viewController: ClubDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: ClubData.Something.Response)
  {
    let viewModel = ClubData.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
