//
//  ClubInteractor.swift
//  HSE Clubs
//
//  Created by Ярослав Ульяненков on 14.03.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import Alamofire

protocol ClubBusinessLogic
{
  func loadClub(request: ClubData.Info.Request)
}

protocol ClubDataStore
{
  //var name: String { get set }
}

class ClubInteractor: ClubBusinessLogic, ClubDataStore
{
  var presenter: ClubPresentationLogic?
  var worker: ClubWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func loadClub(request: ClubData.Info.Request)
  {
      guard let url = RequestRoutes.getRoute(.getClub(request.id)) else {return}
      AF.request(url, method: .get).responseDecodable(of: ClubData.Info.Response.self) { response in
          switch response.result {
          case .success:
              guard let clubs = response.value else { return }
              DispatchQueue.main.async {
                  self.presenter?.presentClub(response: clubs)
              }
          case .failure(let error):
              print("Error:", error)
          }
      }
  }
}
