//
//  ClubViewController.swift
//  HSE Clubs
//
//  Created by Ярослав Ульяненков on 14.03.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import SnapKit

protocol ClubDisplayLogic: AnyObject
{
    func displaySomething(viewModel: ClubData.Something.ViewModel)
}

class ClubViewController: UIViewController, ClubDisplayLogic
{
    var interactor: ClubBusinessLogic?
    var router: (NSObjectProtocol & ClubRoutingLogic & ClubDataPassing)?
    var clubName: String? = "HSE JEWS"
    var clubDescription: String? = "Клуб создан для всех потомков Авраама и для тех, кто хочет вернуться на землю Обетованную"
    var avatar: UIImage? = UIImage(named: "fkn")
    
    let eventsTitle: UILabel = {
        let label = UILabel()
        label.text = "Мероприятия"
        label.font = UIFont.systemFont(ofSize: 24, weight: .semibold)
        label.textColor = UIColor(red: 0, green: 47/225.0, blue: 141/225.0, alpha: 100)
        return label
    }()
    
    // MARK: Object lifecycle
    
    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?)
    {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }
    
    required init?(coder aDecoder: NSCoder)
    {
        super.init(coder: aDecoder)
        setup()
    }
    
    // MARK: Setup
    
    private func setup()
    {
        let viewController = self
        let interactor = ClubInteractor()
        let presenter = ClubPresenter()
        let router = ClubRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }
    
    // MARK: Routing
    
    override func prepare(for segue: UIStoryboardSegue, sender: Any?)
    {
        if let scene = segue.identifier {
            let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
            if let router = router, router.responds(to: selector) {
                router.perform(selector, with: segue)
            }
        }
    }
    
    // MARK: View lifecycle
    
    override func viewDidLoad()
    {
        super.viewDidLoad()
        view.backgroundColor = .white
        
        let clubName = ClubNameView(frame: CGRect(x: 0, y: 0, width: view.bounds.width - 40, height: 200), name: clubName, avatar: avatar, description: clubDescription)
        
        view.addSubview(clubName)
        
        clubName.snp.makeConstraints { make in
            make.top.equalTo(view.safeAreaLayoutGuide).offset(20)
            make.left.equalToSuperview().offset(20)
//            make.height.equalTo(150)
            make.width.equalToSuperview().offset(-40)
        }
        
        let administratorName = AdministratorView(frame: CGRect(x: 0, y: 0, width: view.bounds.width - 40, height: 200), name: "Киану Чарльз Ривз", vk: "@kianu.reeves", telegram: "knchrvs", email: "kianu@reeves.com", avatar: UIImage(named: "kianu"))
        
        view.addSubview(administratorName)
        administratorName.snp.makeConstraints { make in
            make.top.equalTo(clubName.snp.bottom).offset(20)
            make.left.equalToSuperview().offset(20)
            make.right.equalToSuperview().offset(20)
            make.height.equalTo(100)
        }
        
        view.addSubview(eventsTitle)
        
        eventsTitle.snp.makeConstraints { make in
            make.top.equalTo(administratorName.snp.bottom).offset(20)
            make.left.equalToSuperview().offset(20)
        }
        
        
        let event = EventView(frame: CGRect(x: 0, y: 0, width: 350, height: 150), name: "Знакомство с клубом", description: "На первой встречи клуба мы познакомимся с алфавитом иврита и изучим иудейский календарь.", date: "01.04.2022 12:30", place: "R204")
        
        view.addSubview(event)
        event.snp.makeConstraints { make in
            make.top.equalTo(eventsTitle.snp.bottom).offset(20)
            make.left.equalToSuperview().offset(20)
            make.width.equalTo(350)
            make.height.equalTo(150)
        }
        doSomething()
    }
    
    override func viewDidAppear(_ animated: Bool) {
        self.tabBarController?.title = "Клуб"
    }
    
    
    // MARK: Do something
    
    //@IBOutlet weak var nameTextField: UITextField!
    
    func doSomething()
    {
        let request = ClubData.Something.Request()
        interactor?.doSomething(request: request)
    }
    
    func displaySomething(viewModel: ClubData.Something.ViewModel)
    {
        //nameTextField.text = viewModel.name
    }
}
