//
//  SearchInteractor.swift
//  HSE Clubs
//
//  Created by Ярослав Ульяненков on 13.03.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SearchBusinessLogic
{
    func loadClubs()
}

protocol SearchDataStore
{
    var clubs: [Club] { get set }
}

class SearchInteractor: SearchBusinessLogic, SearchDataStore
{
    var presenter: SearchPresentationLogic?
    var worker: SearchWorker?
    var clubs = [
//        Club(name: "Фан-клуб Гринкруга", description: "Хэйтим С# вместе"),
        Club(name: "HSE Chess", description: "Chess - game of life"),
        Club(name: "Чайный клуб НИУ ВШЭ", description: "Лучше кофе."),
        Club(name: "Клуб дебатов ВШЭ", description: "Just debating around"),
        Club(name: "Го-клуб НИУ ВШЭ", description: "Го-клуб Вышки снова с вами!"),
        Club(name: "Турклуб ВШЭ", description: "Сделано в МИЭМ"),
        Club(name: "Ролевой клуб ВШЭ", description: "Ролевое сообщество Вышки."),
        Club(name: "HSE JEWS", description: "Еврейский клуб НИУ ВШЭ"),
        Club(name: "HSE MAFIA", description: "Клуб игры в профессиональную мафию"),
        Club(name: "HSE Case School", description: "Подготовка к кейс-чемпионатам"),
    ]
    
    func loadClubs()
    {
        print("Load clubs")
        presenter?.presentClubs(clubs: clubs)
    }
}
