//
//  SearchModels.swift
//  HSE Clubs
//
//  Created by Ярослав Ульяненков on 13.03.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

struct Club {
    var name: String
    var description: String
    var avatar: UIImage?
    
    init(name: String, description: String) {
        self.name = name
        self.description = description
        avatar = UIImage(named: "fkn")
    }
}
