//
//  SearchPresenter.swift
//  HSE Clubs
//
//  Created by Ярослав Ульяненков on 13.03.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MyClubsPresentationLogic
{
    func presentClubs(clubs: [MyClubModel])
}

class MyClubsPresenter: MyClubsPresentationLogic
{
    weak var viewController: MyClubsDisplayLogic?
    
    // MARK: Do something
    
    func presentClubs(clubs: [MyClubModel])
    {
        var clubViews: [MyClub] = []
        for club in clubs {
            clubViews.append(MyClub(name: club.name ?? "Пусто", description: club.description ?? "Пусто", id: club.id, events: club.events))
        }
        viewController?.displayClubs(clubs: clubViews)
    }
}
