//
//  SearchModels.swift
//  HSE Clubs
//
//  Created by Ярослав Ульяненков on 13.03.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

struct MyClubModel: Codable {
    var administratorID: Int
    var avatarPath: String?
    var description: String?
    var id: Int
    var events: [ClubData.Info.Event]
    var name: String?
}

struct MyClub {
    var name: String
    var description: String
    var avatar: UIImage?
    var events: [ClubData.Info.Event]
    var id: Int
    
    init(name: String, description: String, id: Int, events: [ClubData.Info.Event]) {
        self.name = name
        self.id = id
        self.description = description
        avatar = UIImage(named: "fkn")
        self.events = events
    }
}
