//
//  SearchInteractor.swift
//  HSE Clubs
//
//  Created by Ярослав Ульяненков on 13.03.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import Alamofire

protocol MyClubsBusinessLogic
{
    func loadClubs()
}

protocol MyClubsDataStore
{
    var clubs: [MyClub] { get set }
}

class MyClubsInteractor: MyClubsBusinessLogic, MyClubsDataStore
{
    var presenter:MyClubsPresentationLogic?
    var worker: MyClubsWorker?
    var clubs: [MyClub] = [
//        Club(name: "Фан-клуб Гринкруга", description: "Хэйтим С# вместе"),
//        Club(name: "HSE Chess", description: "Chess - game of life"),
//        Club(name: "Чайный клуб НИУ ВШЭ", description: "Лучше кофе."),
//        Club(name: "Клуб дебатов ВШЭ", description: "Just debating around"),
//        Club(name: "Го-клуб НИУ ВШЭ", description: "Го-клуб Вышки снова с вами!"),
//        Club(name: "Турклуб ВШЭ", description: "Сделано в МИЭМ"),
//        Club(name: "Ролевой клуб ВШЭ", description: "Ролевое сообщество Вышки."),
//        Club(name: "HSE JEWS", description: "Еврейский клуб НИУ ВШЭ"),
//        Club(name: "HSE MAFIA", description: "Клуб игры в профессиональную мафию"),
//        Club(name: "HSE Case School", description: "Подготовка к кейс-чемпионатам"),
    ]
    
    func loadClubs()
    {
        guard let url = RequestRoutes.getRoute(.getClubs) else {return}
        AF.request(url, method: .get).responseDecodable(of: [MyClubModel].self) { response in
            switch response.result {
            case .success:
                guard let clubs = response.value else { return }
                DispatchQueue.main.async {
                    self.presenter?.presentClubs(clubs: clubs)
                }
            case .failure(let error):
                print("Error:", error)
            }
        }
    }
}
